# Generated by Django 5.1.3 on 2024-11-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
